apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

charts:
- name: db-secret-argo
  override:
    postgres.username: postgres
    postgres.password: tacopassword

- name: db-secret-decapod-db
  override:
    postgres.username: postgres
    postgres.password: tacopassword

- name: postgresql
  override:
    persistence.storageClass: taco-storage
    persistence.size: 10Gi

- name: argo-workflows-operator
  override:
    controller.persistence.nodeStatusOffLoad: true
    controller.persistence.archive: true
    controller.persistence.postgresql.host: postgresql.decapod-db
    controller.telemetryConfig.enabled: true
    controller.metricsConfig.enabled: true 
    server.servicePortName: http
